config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'# setando a pagina inicial, nomedapasta#arquivohtml

  resources :users, except: [:new], path:"usuarios"
  #cria as rotas para os usuários, menos as que estiverem no except
  #a função resources cria 7 rotas referente ao usuário

  get '/cadastro', to: 'users#new'
  #a get pega a informação submitada no link cadastro para a função

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'

  delete '/logout', to: "sessions#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :password,presence: true, length: { minimum: 6 } # validates presence diz que não pode estar vazio, length possui parametros que determinam o tamanho, sendo minimo ou máximo
    #Utilização da lib bcrypt
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    before_action :barra_acesso_a_logados, only: [:new]
    before_action :barra_acesso_a_deslogados, only: [:destroy]
    def new

    end

    def create
        user = User.find_by(email: params[:session][:email])
        if user && user.authenticate(params[:session][:password])
            log_in(user)
            redirect_to user
        else
            render 'new'
        end
    end

    def destroy
        log_out
        redirect_to root_path
    end

    def barra_acesso_a_logados
        if logged_in?
            redirect_to current_user
        end
    end

    def barra_acesso_a_deslogados
        if !logged_in?
            redirect_to root_path
        end
    end



end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    def home
        render 'home'
    end

    private

    def barra_acesso_a_deslogados
        if !logged_in?
            redirect_to root_path
        end
    end

    def barra_acesso_a_logados
        if logged_in?
            redirect_to current_user
        end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :barra_acesso_a_deslogados, except: [:new, :create]
    before_action :barra_acesso_a_logados, only: [:new]


    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            log_in @user
            redirect_to @user
        else
            render 'new'
        end
    end

    def index
    end

    def show
        @user = User.find(params[:id])
    end

    private

    def user_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    def barra_acesso_a_deslogados
        if !logged_in?
            redirect_to root_path
        end
    end

    def barra_acesso_a_logados
        if logged_in?
            redirect_to current_user
        end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in(user)
        session[:user_id] = user.id
    end

    def current_user
        if session[:user_id]
            if @current_user.nil?# .nil? é uma função do ruby, que verifica se tal parametro  é null ou não
                @current_user = User.find_by(id: session[:user_id])
            else
                @current_user
            end
        end
    end

    def logged_in?
        !current_user.nil?
    end

    def log_out
        session.delete(:user_id)
        @current_user = nil
    end

    
   
    

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Login</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% if logged_in? %>
    <%= link_to "Sair", logout_path, method: :delete %>
  <% end %>
    <%= yield %>
  </body>
</html>

app/views/static_pages/home.html.erb
<h1>Olá! Seja bem vindo ao nosso site.</h1>


<%= link_to "Cadastre-se agora!", cadastro_path%> ou
<%= link_to "Logue agora!", login_path%>

app/views/users/_form.html.erb
<%=  form_with(model: user, local: true) do |form| %> <!--estabelece um formulario com o model dedicado ao usuário, o local serve para indicar que o server é nativo-->

<div class="field">
    <%= form.label :name, "Nome"%>
    <%= form.text_field :name %>
</div>



<div class="field">
    <%= form.label :email, "Email"%>
    <%= form.email_field :email %>
</div>

<div class="field">
    <%= form.label :password, "Senha"%>
    <%= form.password_field :password %>
</div>
<br>
<div class="field">
    <%= form.label :password_confirmation, "Confirmar Senha"%><br>
    <%= form.password_field :password_confirmation %>
</div>

<div class="actions">
    <%= form.submit "Cadastrar"%>
</div>

<% end %>

app/views/users/index.html.erb
<h2> Login efetuado </h2>

app/views/users/new.html.erb
<h1>Cadastre-se!</h1>

<%= render 'form', user: @user %> <!--chama o conteúdo do outro site -->

app/views/users/show.html.erb
<%= @user.name %>
<%= @user.email %>